version: '3'

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    hostname: redis

  red-server:
    container_name: red-server
    image: httpd:2.4.29
    hostname: red-server
    depends_on:
      - php-fpm
    volumes:
      - ./logs:/usr/local/apache2/logs/
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/php-fpm.conf:/usr/local/apache2/conf/conf.d/php-fpm.conf

  blue-server:
    container_name: blue-server
    image: httpd:2.4.29
    hostname: blue-server
    depends_on:
      - php-fpm
    volumes:
      - ./logs:/usr/local/apache2/logs/
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/php-fpm.conf:/usr/local/apache2/conf/conf.d/php-fpm.conf

  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    image: php:7.1-fpm-alpine
    depends_on:
      - redis
    volumes:
      - ./php/:/var/www/html/
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: '6379'

  load-balancer:
    container_name: load-balancer
    image: nginx:1.13.7
    depends_on:
      - blue-server
      - red-server
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/usr/local/logs
    ports:
      - 8081:80

  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:6.0.0
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'

  logstash:
    container_name: logstash
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:6.0.0
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/local/logs

  jenkins:
    container_name: jenkins
    hostname: jenkins
    build:
      context: jenkins
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
    volumes:
      - ./jenkins/data/workspace:/var/jenkins_home/workspace
      - ./jenkins/data/users:/var/jenkins_home/users
      - ./jenkins/data/jobs:/var/jenkins_home/jobs
      - ./jenkins/curator.yml:/curator.yml
      - ./jenkins/delete_index.yml:/delete_index.yml
    ports:
      - 8082:8080
    user: jenkins
